#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

name: "Strapi Docker - TrustBloc Fork"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Publish:
    name: Publish image
    # if: github.event_name == 'push' && (github.repository == 'trustbloc/strapi-docker' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          yarn install
          ./bin/build.js
